exports.shippingProvider = require('./shippingProvider')
exports.imageProvider = require('./imageProvider')
exports.taxProvider = require('./taxProvider')
exports.geolocationProvider = require('./geolocationProvider')
exports.renderService = require('./renderService')
