exports.product = require('./product')
exports.variant = require('./variant')
exports.image = require('./image')
exports.add = require('./add')
exports.update = require('./update')
exports.remove = require('./remove')
